services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    image: ${ECR_REGISTRY}/testing/fast_api-backend:${IMAGE_TAG}  # Updated ECR image reference
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - task-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: ${ECR_REGISTRY}/testing/fast_api-frontend:${IMAGE_TAG}  # Updated ECR image reference
    container_name: node-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
