version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - task-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: node-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
