name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  IMAGE_TAG: latest
  CLUSTER_NAME: testing
  AWS_REGION: eu-north-1
  EXECUTION_ROLE_ARN: arn:aws:iam::354918374652:role/ecsTaskExecutionRole
  VPC_SUBNETS: vpc-017328606a774e563  # Replace with your subnet IDs
  SECURITY_GROUP: sg-08721e8cd1e5d3851  # Replace with your security group ID

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::354918374652:role/GITHUB_deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Images
        run: |
          docker compose build
          docker compose push

      - name: Deploy Backend Service
        run: |
          # Create backend task definition JSON
          cat <<EOF > backend-task-def.json
          {
            "family": "fastapi-backend",
            "executionRoleArn": "${{ env.EXECUTION_ROLE_ARN }}",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "1024",
            "memory": "2048",
            "containerDefinitions": [
              {
                "name": "backend",
                "image": "${{ env.ECR_REGISTRY }}/testing/fast_api:backend-${{ env.IMAGE_TAG }}",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 8000,
                    "hostPort": 8000,
                    "protocol": "tcp"
                  }
                ],
                "environment": [
                  {"name": "ENV_VAR_NAME", "value": "value"}
                ],
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/fastapi-backend",
                    "awslogs-region": "${{ env.AWS_REGION }}",
                    "awslogs-stream-prefix": "ecs"
                  }
                }
              }
            ]
          }
          EOF

          # Register task definition
          BACKEND_TASK_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://backend-task-def.json \
            --region ${{ env.AWS_REGION }} \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "Backend task ARN: $BACKEND_TASK_ARN"

          # Create or update service
          if aws ecs describe-services --cluster ${{ env.CLUSTER_NAME }} --services fastapi-backend-service --region ${{ env.AWS_REGION }} >/dev/null 2>&1; then
            echo "Updating existing backend service"
            aws ecs update-service \
              --cluster ${{ env.CLUSTER_NAME }} \
              --service fastapi-backend-service \
              --task-definition $BACKEND_TASK_ARN \
              --region ${{ env.AWS_REGION }} \
              --force-new-deployment
          else
            echo "Creating new backend service"
            aws ecs create-service \
              --cluster ${{ env.CLUSTER_NAME }} \
              --service-name fastapi-backend-service \
              --task-definition $BACKEND_TASK_ARN \
              --launch-type FARGATE \
              --desired-count 1 \
              --network-configuration "awsvpcConfiguration={subnets=[${{ env.VPC_SUBNETS }}],securityGroups=[${{ env.SECURITY_GROUP }}],assignPublicIp=ENABLED}" \
              --region ${{ env.AWS_REGION }}
          fi

      - name: Deploy Frontend Service
        run: |
          # Create frontend task definition JSON
          cat <<EOF > frontend-task-def.json
          {
            "family": "node-frontend",
            "executionRoleArn": "${{ env.EXECUTION_ROLE_ARN }}",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "1024",
            "memory": "2048",
            "containerDefinitions": [
              {
                "name": "frontend",
                "image": "${{ env.ECR_REGISTRY }}/testing/fast_api:frontend-${{ env.IMAGE_TAG }}",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 3000,
                    "hostPort": 3000,
                    "protocol": "tcp"
                  }
                ],
                "environment": [
                  {"name": "BACKEND_URL", "value": "http://fastapi-backend-service:8000"},
                  {"name": "ENV_VAR_NAME", "value": "value"}
                ],
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/node-frontend",
                    "awslogs-region": "${{ env.AWS_REGION }}",
                    "awslogs-stream-prefix": "ecs"
                  }
                }
              }
            ]
          }
          EOF

          # Register task definition
          FRONTEND_TASK_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://frontend-task-def.json \
            --region ${{ env.AWS_REGION }} \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "Frontend task ARN: $FRONTEND_TASK_ARN"

          # Create or update service
          if aws ecs describe-services --cluster ${{ env.CLUSTER_NAME }} --services node-frontend-service --region ${{ env.AWS_REGION }} >/dev/null 2>&1; then
            echo "Updating existing frontend service"
            aws ecs update-service \
              --cluster ${{ env.CLUSTER_NAME }} \
              --service node-frontend-service \
              --task-definition $FRONTEND_TASK_ARN \
              --region ${{ env.AWS_REGION }} \
              --force-new-deployment
          else
            echo "Creating new frontend service"
            aws ecs create-service \
              --cluster ${{ env.CLUSTER_NAME }} \
              --service-name node-frontend-service \
              --task-definition $FRONTEND_TASK_ARN \
              --launch-type FARGATE \
              --desired-count 1 \
              --network-configuration "awsvpcConfiguration={subnets=[${{ env.VPC_SUBNETS }}],securityGroups=[${{ env.SECURITY_GROUP }}],assignPublicIp=ENABLED}" \
              --region ${{ env.AWS_REGION }}
          fi