name: Build and Deploy to ECS

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the build

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (Docker multi-platform build)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::354918374652:role/GITHUB_deploy
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Step 5: Build, Tag, and Push Docker Compose Services to ECR
      - name: Build, Tag, and Push Docker Compose Services to ECR
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          IMAGE_TAG: latest
        run: |
          # Build and push images using docker compose
          docker compose build
          docker compose push

      # Step 6: Update ECS Task Definition and Deploys
      - name: Deploy to ECS
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          IMAGE_TAG: latest
          TASK_DEFINITION: test_api      # Set your ECS task family name here
          CLUSTER_NAME: testing          # Set your ECS cluster name here
          SERVICE_NAME: test_api-service-qav2njq3  # Set your ECS service name here
        run: |
          # Update image for both frontend and backend containers in task definition
          jq --arg frontend_image "$ECR_REGISTRY/frontend-latest:$IMAGE_TAG" \
             --arg backend_image "$ECR_REGISTRY/backend-latest:$IMAGE_TAG" \
             'map( if .name == "frontend_container" then .image = $frontend_image elif .name == "backend_container" then .image = $backend_image else . end ) | {containerDefinitions: .}' \
             container-definitions.json > updated-container-definitions.json
      
          # Register new revision of the task definition
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --family $TASK_DEFINITION \
            --cli-input-json file://updated-container-definitions.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
      
          echo "New Task Definition ARN: $NEW_TASK_DEF_ARN"  # Debugging output
      
          # Update ECS service to use the new task definition and force new deployment
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition $NEW_TASK_DEF_ARN \
            --force-new-deployment